### ISSUE TITLE
cannot reach spec when developing locally with current code base

### ISSUE THREAD

**Issue by babslgam** [acdh-oeaw/apis-oebl-irs-devops#60]
![image](https://user-images.githubusercontent.com/14592657/206687941-1f668477-54bd-439f-b51d-70f074b65541.png)

needed by frontend, where the url is still hard coded:
https://github.com/acdh-oeaw/apis-oebl-research-tool-front-end/blob/cd6b10d336e9a9e1f3511f3602d3d02dd49054dd/package.json#L13

**Comment by babslgam** [comment]
@sennierer 
https://github.com/tfranzel/drf-spectacular/issues/816

can you increase the version number here?
https://github.com/acdh-oeaw/apis-core/blob/main/pyproject.toml#L54

**Comment by sennierer** [comment]
we should move to use a sub-module to apis-core in this project.
then in the pyproject.toml use the local path to the sub-module, similar to here: https://github.com/acdh-oeaw/apis-rdf-devops/blob/dev/pyproject.toml#L24 and change these things directly in the sub-module.
There was an issue with more recent drf-spectacular versions that prevented us from upgrading.
